[profile.default]
src = 'src'
out = 'out'
test = 'test'
libs = ['lib']
solc = "0.8.24"
fs_permissions = [{ access = "read", path = "./broadcast" }]
gas_reports = ["Foo"]

[rpc_endpoints]
apechain = "https://apechain.calderachain.xyz/http"

# No etherscan configuration since we don't need it for ApeChain
